- name: "DORA Reporting"
  regulationFullName: "Digital Operational Resilience Act"
  slug: "dora"
  url: "products/dora/"
  price: "€599"
  price_period: "/year"
  status: "Active Product"
  color: "brand-green"
  hover_color: "brand-dark"
  card_border: "border-2 border-brand-green"
  image: /assets/images/golden-padlock.jpg
  features:
    - "Complete DORA compliance solution"
    - "Register of Information templates"
    - "Full report validation & conversion"
    - "Professional support"
  button_text: "Learn More"

- name: "IRRD Reporting"
  regulationFullName: "Insurance Recovery and Resolution Directive"
  slug: "irrd"
  url: "products/irrd/"
  price: "Free"
  price_period: " in Beta"
  status: "Beta Version"
  color: "blue-500"
  hover_color: "blue-600"
  card_border: ""
  image: /assets/images/ducks.jpg
  features:
    - "Use the first draft reporting taxonomy"
    - "Early access to the new templates"
    - "Provide feedback to EIOPA by 31&nbsp;October&nbsp;2025"
  button_text: "Learn More"

- name: "PRA Liquidity"
  regulationFullName: "Bank of England Insurance Liquidity"
  slug: "pra-liquidity"
  url: "products/pra-liquidity/"
  price: "Free"
  price_period: " in Beta"
  status: "Beta Version"
  color: "purple-500"
  hover_color: "purple-600"
  card_border: ""
  image: /assets/images/money-pounds.jpg
  features:
    - "Liquidity reporting for large insurers"
    - "Early access to the new templates"
    - "Get ready for the first reporting date in 2026"
  button_text: "Learn More"