- name: "DORA Reporting"
  regulationFullName: "Digital Operational Resilience Act"
  slug: "dora"
  url: "products/dora/"
  price: "€600"
  price_period: "/year"
  status: "Active Product"
  color: "brand-green"
  hover_color: "brand-dark"
  card_border: "border-2 border-brand-green"
  image: /assets/images/golden-padlock.jpg
  image_alt_text: "A combination padlock resting on a keyboard with some chip and pin cards"
  features:
    - "Complete DORA compliance solution"
    - "Register of Information templates"
    - "Full report validation & conversion"
    - "Professional support"
  button_text: "Learn More"

- name: "Lloyd's Schedule 3"
  regulationFullName: "Lloyd's of London Schedule 3 Data"
  slug: "lloyds-schedule-3"
  url: "products/lloyds-schedule-3/"
  price: "£1,100"
  price_period: " /year"
  status: "Active Product"
  color: "purple-500"
  hover_color: "purple-600"
  card_border: ""
  image: /assets/images/lloyds.jpg
  image_alt_text: "A view of the Lloyd's of London building looking up from ground level with a blue sky behind"
  features:
    - "Schedule 3 data template to XBRL conversion"
    - "Use the Lloyd's Excel templates"
    - "Fast and secure conversion with no software installation required"
  button_text: "Learn More"

- name: "PRA Liquidity"
  regulationFullName: "Bank of England Insurance Liquidity"
  slug: "pra-liquidity"
  url: "products/pra-liquidity/"
  price: "Free"
  price_period: " in Beta"
  status: "Beta Version"
  color: "purple-500"
  hover_color: "purple-600"
  card_border: ""
  image: /assets/images/money-pounds.jpg
  image_alt_text: "Various denomination UK Pound notes spread out across a flat surface"
  features:
    - "Liquidity reporting for large insurers"
    - "Early access to the new templates"
    - "Get ready for the first reporting date in 2026"
  button_text: "Learn More"

- name: "IRRD Reporting"
  regulationFullName: "Insurance Recovery and Resolution Directive"
  slug: "irrd"
  url: "products/irrd/"
  price: "Free"
  price_period: " in Beta"
  status: "Beta Version"
  color: "blue-500"
  hover_color: "blue-600"
  card_border: ""
  image: /assets/images/ducks.jpg
  image_alt_text: "A line of rubber ducks all facing the same direction on a blue background"
  features:
    - "Use the first draft reporting taxonomy"
    - "Early access to the new templates"
    - "Provide feedback to EIOPA by 31&nbsp;October&nbsp;2025"
  button_text: "Learn More"