- name: "DORA Reporting"
  description: "Digital Operational Resilience Act"
  url: "products/dora/"
  image: /assets/images/golden-padlock.jpg
  image_alt_text: "A combination padlock resting on a keyboard with some chip and pin cards"
  features:
    - "Complete DORA compliance solution"
    - "Register of Information templates"
    - "Full report validation & conversion"
    - "Professional support"
  order: 10

- name: "Lloyd's Schedule 3"
  description: "Lloyd's of London Schedule 3 Data"
  url: "products/lloyds-schedule-3/"
  image: /assets/images/lloyds.jpg
  image_alt_text: "A view of the Lloyd's of London building looking up from ground level with a blue sky behind"
  features:
    - "Schedule 3 data template to XBRL conversion"
    - "Use the Lloyd's Excel templates"
    - "Fast and secure conversion with no software installation required"
  order: 60

- name: "PRA Liquidity"
  description: "Bank of England Insurance Liquidity"
  url: "products/pra-liquidity/"
  image: /assets/images/money-pounds.jpg
  image_alt_text: "Various denomination UK Pound notes spread out across a flat surface"
  features:
    - "Liquidity reporting for large insurers"
    - "Early access to the new templates"
    - "Get ready for the first reporting date in 2026"
  order: 50

- name: "UK Statistical Forms"
  description: "Bank of England Statistical Reporting"
  url: "products/boe-statistics/"
  image: /assets/images/bank-of-england-wide.jpg
  image_alt_text: "A wide angle photo of the Bank of England with a blue sky"
  features:
    - "Updated to the final 1.3.1 taxonomy"
    - "Full validations included"
    - "Take part in the Spring 2026 UAT window"
  order: 30

- name: "IRRD Reporting"
  description: "Insurance Recovery and Resolution Directive"
  url: "products/irrd/"
  image: /assets/images/ducks.jpg
  image_alt_text: "A line of rubber ducks all facing the same direction on a blue background"
  features:
    - "Use the first draft reporting taxonomy"
    - "Early access to the new templates"
    - "Provide feedback to EIOPA by 31&nbsp;October&nbsp;2025"
  order: 40

- name: "Strong and Simple"
  description: "The simplified capital regime for Small Domestic Deposit Takers (SDDTs)"
  url: "products/strong-and-simple/"
  image: /assets/images/chain.jpg
  image_alt_text: "A black and white photo of a close-up of a section of a large metal chain"
  features:
    - "Test the draft reporting taxonomy"
    - "Early access to the new templates"
    - "Get ready to start reporting from 31&nbsp;December&nbsp;2026"
  order: 20
